-- 관리자 계정 정보
CREATE TABLE TBL_ADMIN 
(
    SEQ NUMBER PRIMARY KEY, -- 관리자 번호
    ID VARCHAR2(50) NOT NULL, -- 관리자 ID
    PW VARCHAR2(50) NOT NULL -- 관리자 PW
);

-- 교사 계정 정보
CREATE TABLE TBL_TEACHER
(
    SEQ NUMBER PRIMARY KEY, -- 교사 번호
    NAME VARCHAR2(30) NOT NULL, -- 교사 이름
    ID VARCHAR2(50) NOT NULL, -- 교사  ID
    SSN VARCHAR2(14) NOT NULL, -- 교사 주민번호(PW로사용)
    TEL VARCHAR2(15) NOT NULL -- 교사 전화번호
);

-- 교육생 계정 정보
CREATE TABLE TBL_STUDENT
(
    SEQ NUMBER PRIMARY KEY, -- 학생 번호
    NAME VARCHAR2(30) NOT NULL, -- 학생 이름
    ID VARCHAR2(50) NOT NULL, -- 학생 ID
    SSN VARCHAR2(14) NOT NULL, -- 학생 주민번호(PW로사용)
    TEL VARCHAR2(15) NOT NULL, -- 학생 전화번호
    ACCOUNT VARCHAR2(50) NULL, -- 학생 계좌
    REGDATE DATE DEFAULT SYSDATE NOT NULL  -- 학생 등록일
);

-- 과정 정보
CREATE TABLE TBL_COURSE
(
    SEQ NUMBER PRIMARY KEY, -- 과정 번호
    NAME VARCHAR2(200) NOT NULL, -- 과정 이름
    PERIOD NUMBER NOT NULL  -- 과정 기간    
);

-- 과목 정보
CREATE TABLE TBL_SUBJECT
(
    SEQ NUMBER PRIMARY KEY, -- 과목 번호
    NAME VARCHAR2(200) NOT NULL, -- 과목 이름
    PERIOD NUMBER NOT NULL,  -- 과목 기간    
    BOOKSEQ NUMBER NOT NULL REFERENCES TBL_BOOK(SEQ) -- 교재 번호
);

-- 강의실 정보
CREATE TABLE TBL_CLASSROOM
(
    SEQ NUMBER PRIMARY KEY, -- 강의실 번호
    MAXIMUM NUMBER NOT NULL -- 인원 수
);

-- 교재 정보
CREATE TABLE TBL_BOOK
(
    SEQ NUMBER PRIMARY KEY, -- 교재 번호
    NAME VARCHAR2(100) NOT NULL, -- 교재 명
    PUBLISHER VARCHAR2(50) NOT NULL -- 출판사 명
);

-----------------------------------------------------------------------

-- 개설 과정 정보
CREATE TABLE TBL_OPEN_COURSE
(
    SEQ NUMBER PRIMARY KEY, -- 개설 과정 번호
    STARTDATE DATE NOT NULL, -- 개설 과정 시작 날짜
    ENDDATE DATE NOT NULL, -- 개설 과정 종료 날짜
    CRSSEQ NUMBER NOT NULL REFERENCES TBL_COURSE(SEQ) -- 과정 번호
);

-- 개설 과목 정보
CREATE TABLE TBL_OPEN_SUBJECT
(
    SEQ NUMBER PRIMARY KEY, -- 개설 과목 번호
    STARTDATE DATE NOT NULL, -- 개설 과목 시작 날짜
    ENDDATE DATE NOT NULL, -- 개설 과목 종료 날짜
    OCRSSEQ NUMBER NOT NULL REFERENCES TBL_OPEN_COURSE(SEQ), -- 개설 과정 번호
    AVAILSEQ NUMBER NOT NULL REFERENCES TBL_AVAIL_SUBJECT(SEQ) -- 배정 정보    
);

-- 과정별 과목 정보
CREATE TABLE TBL_COURSE_SUBJECT
(
    SEQ NUMBER PRIMARY KEY, -- 과정별 과목 번호
    CRSSEQ NUMBER NOT NULL REFERENCES TBL_COURSE(SEQ), -- 과정 번호
    SUBSEQ NUMBER NOT NULL REFERENCES TBL_SUBJECT(SEQ)  -- 과목 번호
);

-- 수강신청 정보
CREATE TABLE TBL_APPLY
(
    SEQ NUMBER PRIMARY KEY, -- 수강 신청 번호
    STATUS DATE, --수강신청 상태
    STUSEQ NUMBER NOT NULL REFERENCES TBL_STUDENT(SEQ), -- 교육생 번호
    OCRSSEQ NUMBER NOT NULL REFERENCES TBL_OPEN_COURSE(SEQ) -- 개설 과정 번호
);

-- 강의 가능 과목 정보
CREATE TABLE TBL_AVAIL_SUBJECT
(
    SEQ NUMBER PRIMARY KEY, -- 강의 가능 과목 번호
    TEASEQ NUMBER NOT NULL REFERENCES TBL_TEACHER(SEQ), -- 교사 번호
    SUBSEQ NUMBER NOT NULL REFERENCES TBL_SUBJECT(SEQ) -- 과목 번호
);

-- 개설된 강의실 정보
CREATE TABLE TBL_OPEN_CLASSROOM
(
    SEQ NUMBER PRIMARY KEY, -- 개설된 강의실 번호
    OCRSSEQ NUMBER NOT NULL REFERENCES TBL_OPEN_COURSE(SEQ), -- 개설 과정 번호
    ROOMSEQ NUMBER NOT NULL REFERENCES TBL_CLASSROOM(SEQ) -- 강의실 번호   
);

-- 성적
CREATE TABLE TBL_SCORE
(
    SEQ NUMBER PRIMARY KEY, -- 성적 번호
    WRITE NUMBER, -- 필기 성적
    PERFORMANCE NUMBER, -- 실기 성적
    ATTEND NUMBER, -- 출결 점수
    OSUBSEQ NUMBER NOT NULL REFERENCES TBL_OPEN_SUBJECT(SEQ), -- 개설 과목 번호
    STESEQ NUMBER NOT NULL REFERENCES TBL_STUDENT(SEQ) -- 교육생 번호
);

-- 배점
CREATE TABLE TBL_POINT
(
    SEQ NUMBER PRIMARY KEY, -- 배점 번호
    WRITE NUMBER, -- 필기 배점
    PERFORMANCE NUMBER, -- 실기 배점
    ATTEND NUMBER DEFAULT 20 NOT NULL, -- 출결 배점
    OSUBSEQ NUMBER NOT NULL REFERENCES TBL_OPEN_SUBJECT(SEQ) --  개설 과목 번호
);

-- 시험
CREATE TABLE TBL_TEST
(
    SEQ NUMBER PRIMARY KEY, -- 시험 번호
    TESTFILE VARCHAR2(500), -- 시험 파일
    TESTDATE DATE, -- 시험 날짜
    OSUBSEQ NUMBER NOT NULL REFERENCES TBL_OPEN_SUBJECT(SEQ) -- 개설 과목 번호
);

-- 국비 지원
CREATE TABLE TBL_SUPPORT
(
    SEQ NUMBER PRIMARY KEY, --  국비 지원 번호
    TYPE VARCHAR2(50) NOT NULL, -- 국비 지원 종류(취성패,내일배움,재직자,자비)
    DEPDATE DATE, -- 지급일
    APPSEQ NUMBER NOT NULL REFERENCES TBL_APPLY(SEQ) -- 수강 신청 번호
);

-- 취업
CREATE TABLE TBL_EMPLOYMENT
(
     SEQ NUMBER PRIMARY KEY, -- 취업 번호
     COMPANY VARCHAR2(30), -- 회사명
     SALARY NUMBER, -- 연봉
     APPSEQ NUMBER NOT NULL REFERENCES TBL_APPLY(SEQ) -- 수강 신청 번호
);

-- 교사 평가
CREATE TABLE TBL_TEACHER_SCORE
(
    SEQ NUMBER PRIMARY KEY, -- 교사 평가 번호
    SCORE NUMBER,  -- 평점
    OSUBSEQ NUMBER NOT NULL REFERENCES TBL_OPEN_SUBJECT(SEQ) -- 개설 과목 번호
);

---------------------------------------------------------

-- 관리자 근태
CREATE TABLE TBL_ATTEND_ADMIN
(
    SEQ NUMBER PRIMARY KEY, -- 관리자 근태 번호
    DAYS DATE NOT NULL, -- 날짜
    INTIME DATE, -- 출근 시간
    OUTTIME DATE -- 퇴근 시간
);

-- 교사 근태
CREATE TABLE TBL_ATTEND_TEACHER
(
    SEQ NUMBER PRIMARY KEY, -- 교사 근태 번호
    DAYS DATE NOT NULL, -- 날짜
    INTIME DATE, -- 출근 시간
    OUTTIME DATE, -- 퇴근 시간
    STATUS VARCHAR2(10), -- 상태(병가,외출,기타)
    ADMSEQ NUMBER NOT NULL REFERENCES TBL_TEACHER(SEQ) -- 교사 번호
);

-- 교육생 근태
CREATE TABLE TBL_ATTEND_STUDENT
(
    SEQ NUMBER PRIMARY KEY, -- 교육생 근태 번호
    DAYS DATE NOT NULL, -- 날짜
    INTIME DATE, -- 출근 시간
    OUTTIME DATE, -- 퇴근 시간
    STATUS VARCHAR2(10), -- 상태(병가,외출,기타)
    APPSEQ NUMBER NOT NULL REFERENCES TBL_APPLY(SEQ) -- 수강 신청 번호
);

--------------------------------------------------------

-- 관리자 열 체크
CREATE TABLE TBL_COVID19_ADMIN
(
    SEQ NUMBER PRIMARY KEY, -- 관리자 열 체크 번호
    AMTEMP NUMBER, -- 오전 체온
    PMTEMP NUMBER, -- 오후 체온
    ATTSEQ NUMBER NOT NULL REFERENCES TBL_ATTEND_ADMIN(SEQ) -- 근태 번호
);

-- 교사 열 체크
CREATE TABLE TBL_COVID19_TEACHER
(
    SEQ NUMBER PRIMARY KEY, -- 교사 열 체크 번호
    AMTEMP NUMBER, -- 오전 체온
    PMTEMP NUMBER, -- 오후 체온
    ATTSEQ NUMBER NOT NULL REFERENCES TBL_ATTEND_TEACHER(SEQ) -- 근태 번호
);

-- 교육생 열 체크
CREATE TABLE TBL_COVID19_STUDENT
(
    SEQ NUMBER PRIMARY KEY, -- 교육생 열 체크 번호
    AMTEMP NUMBER, -- 오전 체온
    PMTEMP NUMBER, -- 오후 체온
    ATTSEQ NUMBER NOT NULL REFERENCES TBL_ATTEND_STUDENT(SEQ) -- 근태 번호
);

COMMIT;




